### PR TITLE
Add a GitHub link to the problemset

### PR DESCRIPTION
**Pull request by matous-volf**

### CODE REVIEW

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
jeste me napadlo target="_blank"?

**Comment by zapotocnylubos** [comment]
> target="_blank"

jo 👍

**Comment by zapotocnylubos** [comment]
mozna jeste nejaky margin dolu? (at je vice oddeleney ten titulek + button a zbytek textu)

**Comment by matous-volf** [comment]
@zapotocnylubos hotovo
image

**Comment by matous-volf** [comment]
a mozna anglicky "view on github"?

**Comment by zapotocnylubos** [comment]
@matous-volf jj, anglicky prosim

**Review by zapotocnylubos — APPROVED** [review]

**Pull request merged**
