### PR TITLE
Registration

### PR DESCRIPTION
**Pull request by matous-volf**
- Added new options to configuration.
- Increased length of a configuration name to 64 characters.
- Updated the registration form.

### CODE REVIEW

**Comment by zapotocnylubos** [comment]
posles sem prosim html sniper toho formulare? ten selecto je takovej ... no :D

**Comment by matous-volf** [comment]
```
<form name="user_registration" method="post" class="form-signin">
   <h1 class="h3 mb-3 fw-normal">Register Account</h1>
   <div class="mb-2">
      Enter the following information to register your account with DOMjudge.
   </div>
   <div class="mb-3"><input type="text" id="user_registration_username" name="user_registration[username]" required="required" placeholder="Username" autocomplete="username" class="form-control">        </div>
   <div class="mb-3"><input type="text" id="user_registration_name" name="user_registration[name]" required="required" placeholder="Full name" autocomplete="name" class="form-control">        </div>
   <div class="mb-3"><input type="email" id="user_registration_email" name="user_registration[email]" required="required" placeholder="Email address" autocomplete="email" class="form-control">        </div>
   <fieldset class="mb-3">
      <div id="user_registration_affiliation">
         <div class="form-check"><input type="radio" id="user_registration_affiliation_0" name="user_registration[affiliation]" required="required" class="form-check-input" value="existing">
            <label class="form-check-label required" for="user_registration_affiliation_0">Use existing school</label>
         </div>
         <div class="form-check"><input type="radio" id="user_registration_affiliation_1" name="user_registration[affiliation]" required="required" class="form-check-input" value="new">
            <label class="form-check-label required" for="user_registration_affiliation_1">Add new school</label>
         </div>
      </div>
   </fieldset>
   <div class="mb-3" style="display: none;"><input type="text" id="user_registration_affiliationName" name="user_registration[affiliationName]" placeholder="School name" class="form-control">        </div>
   <input type="hidden" id="user_registration_affiliationShortName" name="user_registration[affiliationShortName]">
   <div class="mb-3" style="display: none;">
      <select id="user_registration_affiliationCountry" name="user_registration[affiliationCountry]" class="form-control form-select form-select select2-hidden-accessible" data-select2-id="user_registration_affiliationCountry" tabindex="-1" aria-hidden="true">
         <option value="" data-select2-id="2">No country</option>
         <option value="ABW">Aruba (ABW)</option>
         <option value="AFG">Afghanistan (AFG)</option>
         <option value="AGO">Angola (AGO)</option>
         <option value="AIA">Anguilla (AIA)</option>
         <option value="ALA">Åland Islands (ALA)</option>
         <option value="ALB">Albania (ALB)</option>
         <option value="AND">Andorra (AND)</option>
         <option value="ARE">United Arab Emirates (ARE)</option>
         <option value="ZWE">Zimbabwe (ZWE)</option>
      </select>
      <span class="select2 select2-container select2-container--bootstrap-5" dir="ltr" data-select2-id="1" style="width: 505.143px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-user_registration_affiliationCountry-container"><span class="select2-selection__rendered" id="select2-user_registration_affiliationCountry-container" role="textbox" aria-readonly="true" title="No country">No country</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>        
   </div>
   <div class="mb-3">
      <select id="user_registration_existingAffiliation" name="user_registration[existingAffiliation]" placeholder="School" class="form-control form-select form-select select2-hidden-accessible" data-select2-id="user_registration_existingAffiliation" tabindex="-1" aria-hidden="true">
         <option value="" data-select2-id="4">-- Select school --</option>
         <option value="1">Utrecht University</option>
         <option value="2">test</option>
      </select>
      <span class="select2 select2-container select2-container--bootstrap-5" dir="ltr" data-select2-id="3" style="width: 505.143px;"><span class="selection"><span class="select2-selection select2-selection--single" role="combobox" aria-haspopup="true" aria-expanded="false" tabindex="0" aria-disabled="false" aria-labelledby="select2-user_registration_existingAffiliation-container"><span class="select2-selection__rendered" id="select2-user_registration_existingAffiliation-container" role="textbox" aria-readonly="true" title="-- Select school --">-- Select school --</span><span class="select2-selection__arrow" role="presentation"><b role="presentation"></b></span></span></span><span class="dropdown-wrapper" aria-hidden="true"></span></span>        
   </div>
   <div class="mb-3"><input type="password" id="user_registration_plainPassword_first" name="user_registration[plainPassword][first]" required="required" placeholder="Password" autocomplete="new-password" spellcheck="false" class="form-control">        </div>
   <div class="mb-3"><input type="password" id="user_registration_plainPassword_second" name="user_registration[plainPassword][second]" required="required" placeholder="Repeat Password" autocomplete="new-password" spellcheck="false" class="form-control">        </div>
   <div class="mb-3">                    <button type="submit" id="user_registration_submit" name="user_registration[submit]" class="btn btn-lg btn-primary btn-block btn">Register</button></div>
   <input type="hidden" id="user_registration__token" name="user_registration[_token]" value="a3cf8dc0aa3c07eb3ae8644a87.-a-N99gM-gO9h08leNU_LQy_0XDSpMZlRadTj-51sjQ.jNrfmZxfrVOKtRZnApZ0X0SLoTGI5ZYmK8EFw51G9VrMmvmYl0GiO9S1Fg">
</form>
```

zkratil jsem ten vycet zemi

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
jinak, proc se prodluzoval limit category name na 64? ja to udelal bezmyslenkovite

**Comment by matous-volf** [comment]
jo a koukam, ze ten select je naopak, ze by to melo skryt opacne pole

**Comment by zapotocnylubos** [comment]
ad. 64 delka, ono mi to pri generovani trimovalo nejak ty jmena

**Comment by zapotocnylubos** [comment]
ad 64, uz vim :) strlen(allow_custom_team_name_registration) == 35

**Comment by zapotocnylubos** [comment]
@matous-volf hodis tedy takovzhly maly popis k te migraci do komentu?

**Review by zapotocnylubos — APPROVED** [review]

**Pull request merged**
