### PR TITLE
Make the cgroups Docker volume not readonly

### PR DESCRIPTION
**Pull request by matous-volf**
same as [this upstream PR](https://github.com/DOMjudge/domjudge/pull/2317).

for [this reason](https://github.com/DOMjudge/domjudge-packaging/issues/170).

### CODE REVIEW

**Comment by zapotocnylubos** [comment]
It will be "solved" by rebasing our fork onto 8.3.0 (#147) since 8.3.0 has this change already merged.

https://github.com/DOMjudge/domjudge/blob/b62fe65651c5b7a418b0d568979ee0a7f1732fda/docker-compose.yml

**Comment by zapotocnylubos** [comment]
@matous-volf for future "backporting", have a look at [git cherry-pick](https://git-scm.com/docs/git-cherry-pick) functionality. It allows you to "copy" some other commit into your branch.

This will then improve the rebasing/merging workflow since the commit hash is the same.

**Comment by matous-volf** [comment]
that means we can close this?

**Comment by zapotocnylubos** [comment]
after we switch to 8.3.0 (not ready yet) yes, then I will close this

**Pull request closed without merging**
