### PR TITLE
Help

### PR DESCRIPTION
**Pull request by matous-volf**

### CODE REVIEW

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
image

**Comment by zapotocnylubos** [comment]
zatim pekne

**Comment by matous-volf** [comment]
napada me misto "help" pouzit "napoveda"?

**Comment by zapotocnylubos** [comment]
@matous-volf jojo, supr a vystiznejsi

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
localhost_12345_public_help (2)

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
image

**Comment by matous-volf** [comment]
ten navbar jeste upravim v oddelenem pr, neni moc responzivni a potrebuje poladit

**Review by zapotocnylubos — APPROVED** [review]

**Pull request merged**
